#!/bin/bash
sudo mv ads1256.so /usr/local/lib/python2.7/dist-packages/ads1256.so
sudo chown root:staff /usr/local/lib/python2.7/dist-packages/ads1256.so
cd ..
sudo rm -r meter_fix/
echo "Fix applied, pH meter restarts now."
sudo init 6

